### ISSUE TITLE
工程clone到本地导入eclipse，run on server后会报SQL 语法错误

### ISSUE THREAD

**Issue by zjg23** [chulung/blog.chukai.pro#1]
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'false' at line 1)] with root cause
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'false' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

**Comment by chulung** [comment]
hi 我更新了sql，没有想到我这小玩意还真的会有人fork_(:3J∠)_
